version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
  pre_build:
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - cd backend
      - docker build -t $DOCKER_USERNAME/nexus-backend:latest .
  post_build:
    commands:
      - docker push $DOCKER_USERNAME/nexus-backend:latest
