version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock &
      - timeout 15 sh -c "until docker info; do echo waiting for docker; sleep 1; done"
  pre_build:
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - cd backend
      - docker build -t $DOCKER_USERNAME/nexus-backend:latest .
  post_build:
    commands:
      - docker push $DOCKER_USERNAME/nexus-backend:latest
