version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock &
      - timeout 15 sh -c "until docker info; do echo waiting for docker; sleep 1; done"
  pre_build:
    commands:
      - printf "%s" Jidnyesh1210 | docker login --username jidnyesh0149 --password-stdin
  build:
    commands:
      - cd backend
      - docker build -t jidnyesh0149/nexus-backend:latest .
  post_build:
    commands:
      - docker push jidnyesh0149/nexus-backend:latest
